//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM_PR_23._106_Oshepkov_PR3_v2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int employee_id { get; set; }
        public string employee_surname { get; set; }
        public string employee_name { get; set; }
        public string employee_patronym { get; set; }
        public int gender_id { get; set; }
        public string employee_phone_number { get; set; }
        public int post_id { get; set; }
        public Nullable<int> authorization_id { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
