//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM_PR_23._106_Oshepkov_PR3_v2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOrderDetails
    {
        public int material_order_details_id { get; set; }
        public int material_order_id { get; set; }
        public int material_id { get; set; }
        public int material_quantity { get; set; }
        public decimal material_order_cost { get; set; }
    
        public virtual MaterialOrder MaterialOrder { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
