//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM_PR_23._106_Oshepkov_PR3_v2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int user_id { get; set; }
        public string employee_surname { get; set; }
        public string employee_name { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public Nullable<int> authorization_id { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
